name: monster-ui-application-callflows
custom_files: null
exposure: private
base_branch: origin/5.3
base_core: monster-ui
template: monster-ui-application.spec.tmpl
package:
  centos7:
    name: monster-ui-application-callflows
    app_name: callflows
    license: 'MPL 2.0'
    group: Productivity/Telephony
    url: 'http://www.2600hz.org/'
    vendor: 2600Hz
  rockylinux8:
    name: monster-ui-application-callflows
    app_name: callflows
    license: 'MPL 2.0'
    group: Productivity/Telephony
    url: 'http://www.2600hz.org/'
    vendor: 2600Hz
    dist: .el8
  rockylinux9:
    name: monster-ui-application-callflows
    app_name: callflows
    license: 'MPL 2.0'
    group: Productivity/Telephony
    url: 'http://www.2600hz.org/'
    vendor: 2600Hz
    dist: .el9
metapackage:
  -
    name: meta-monster-ui
    branch: '5.3'
    package: monster-ui-application-callflows
    type: required
dependencies: null
