---
name: monster-ui-application-callflows
base_branch: origin/master
metapackage:
  - name: meta-monster-ui
    branch: master
    package: monster-ui-application-callflows
    type: required
base_core: monster-ui
template: monster-ui-application.spec.tmpl
package:
  centos7:
    name: monster-ui-application-callflows
    app_name: callflows
    license: "MPL 2.0"
    group: Productivity/Telephony
    url: http://www.2600hz.org/
    vendor: 2600Hz
  app_exchange:
    type: monster-ui-application
    core_app:
      name: monsterui_core
    name: monsterui_callflows
    dependencies: []
